version: '3.0'
services:
  mysql:
    container_name: mysql
    image: mysql
    env_file:
      - w.env
    volumes:
      - mysql_data:/var/lib/mysql:rw
    healthcheck:
      test: "mysqladmin ping -h localhost -u $${MYSQL_USER} --password=$${MYSQL_PASSWORD}"
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
    networks:
      - app_network
    restart: unless-stopped
# Setting of wordpress  
  wordpress:
    container_name: wordpress
    image: wordpress:php7.4-fpm-alpine
    user: www-data
    depends_on:
      - mysql
    env_file:
      - w.env
    volumes:
      - wordpress:/var/www/html:rw
    links:
      - mysql
    networks:
      - app_network
    restart: unless-stopped
# Setting for NGINX
  nginx:
    container_name: nginx
    image: nginx:1.15.12-alpine
    user: nginx
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html:ro
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
    links:
      - wordpress
    ports:
      - "80:80"
    networks:
      - app_network
    restart: unless-stopped
# Named volumes
volumes:
  mysql_data:
  nginx_logs:
  wordpress:
# Networks
networks:
  app_network:
